// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzK5I_1y2993rK7pQWJ6wz75Ed1gQAulw',
    appId: '1:317785362347:web:7c11d5f7525edfa19eccee',
    messagingSenderId: '317785362347',
    projectId: 'user--login',
    authDomain: 'user--login.firebaseapp.com',
    storageBucket: 'user--login.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBADHlLgomiCxQjGo_MnF6x_YKaPLZNab8',
    appId: '1:317785362347:android:7715a552ee4d6ee29eccee',
    messagingSenderId: '317785362347',
    projectId: 'user--login',
    storageBucket: 'user--login.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlu45kfAbBNaTh6Ccfx_Ozijfto4y_jMc',
    appId: '1:317785362347:ios:c6e33f73f6471d359eccee',
    messagingSenderId: '317785362347',
    projectId: 'user--login',
    storageBucket: 'user--login.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU2UM883yAbeV4nzA0WHvDCABa09DdiGg',
    appId: '1:317785362347:web:a6bbfad617768f749eccee',
    messagingSenderId: '317785362347',
    projectId: 'user--login',
    authDomain: 'user--login.firebaseapp.com',
    storageBucket: 'user--login.firebasestorage.app',
  );

}