name: Flutter CI # Name of t

on: # This is the starting point of the work flow and in which event the automation need to run
  push: # Run the jobs when some code is pushed to the given branches
    branches: # Specify the branches that trigger the automation
      - "main" # In my case its main but can be master or any other

  # pull_request: # This code can be added if you want to trigger the automation in pull request as well
  #   branches: 
  #     - "main"

    
jobs:
  flutter_test: # Name of this Job
    name: Run flutter analysis # Name of this step
    runs-on: ubuntu-latest # In which system we are going to do the automation like ubuntu, mac, widows etc.
    steps: # This is the steps of work that going to run of this system
      - uses: actions/checkout@v4 # This step is to clone this project to the virtual machine to run the automation
      - uses: actions/setup-java@v3 # Setting up java for this system environment
        with: # With this options
          java-version: "12.x"
          cache: "gradle"
      - uses: subosito/flutter-action@v2 # This will allow flutter command to run on the system
        with: # With this options
          #flutter-version: "3.29.x" # Specify a flutter version
          flutter-version-file: pubspec.yaml # path to pubspec.yaml
          channel: stable
          cache: true
        
        # Now the flutter command that need to run in the system
      - run: flutter pub get # Get all dependencies
      - run: flutter analyze # Analyze the code
      # - run: flutter test # This line can be added if you had a flutter test
        
                



  